name: PR checks

on:
  pull_request:
    branches:
      - "integration/**"

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  automerge:
    needs: test
    if: needs.test.outputs.passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
